# NOTE: Do not include leading or trailing slashes in the
# subdirectory.
subdirectory = ""

host = "localhost"
port = 6544
scheme = "http"
session_factory = "todo_add_a_secret"
single_app_mode = false
branding = "MED Enterprise Dash"
stewards = "The Peers Community"


# TODO: Just change auto_login to a calculated bool when username has
# a value.
[developer]
auto_login = true
username = "admin"


# https://github.com/python-cas/python-cas
[casclient]
version = "3"
server_url = "https://django-cas-ng-demo-server.herokuapp.com/cas/"


[micro_services.permissions]
url = "http://localhost:6543/apps/api/test/apps_list"
token = "todo_add_a_secret"
mode = "standard" # legacy|standard


[micro_services.status]
url = "http://localhost:6543/apps/status/pub_health"
token = "todo_add_a_secret"
url_integrity = "http://localhost:6543/apps/status/pub_integrity"
